name: Build and Deploy # nombre del trabajo que se va a ejecutar
on: [push] # donde: cuando se realice un push
permissions:
  contents: write
jobs:
  build-and-deploy: # las tareas que se van a ejecutar
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest # correr sobre un servidor ubuntu
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.